### ISSUE TITLE
Unreadable text

### ISSUE THREAD

**Issue by Alex-PK** [Vagdish/planetrs#2]
Please set the text color to #333 instead of #979797, as it is unreadable now.

**Comment by pythoneer** [comment]
I second that. I have good vision and it is really on the edge and at least exhausting to read. I can hardly imagine the problems people have with handicapped vision. 

http://www.planet-rust.com/ fails both the "Web Content Accessibility Guidelines (WCAG) 2.0" AA and AAA Tests

http://webaim.org/resources/contrastchecker/
https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html
https://www.w3.org/TR/WCAG20/

**Comment by Vagdish** [comment]
Thank you. This issue has been fixed with [this commit](https://github.com/Vagdish/planetrs/commit/2f23bada563f9595025f2c6d2c061c9958650c18).

For my defense, I just took a template from os-templates.com and adapted it a bit from planet-rust.com.
