### ISSUE TITLE
Add support for RSS/Atom feeds

### ISSUE THREAD

**Issue by sdroege** [Vagdish/planetrs#3]

**Comment by Vagdish** [comment]
Heya Sebastian,
That's the obvious and natural feature that a planet should provide. I'm already working on Atom feeds support.

I'll update this issue once it's done.

**Comment by remram44** [comment]
Please do! There is simply no way for us to consume your feed if it's not machine readable.

**Comment by Vagdish** [comment]
Done. It's already available on planet-rust.com
Let me now if you have some trouble with the atom feed.

For now, the atom feed is quite minimal.
I intend to make it more complete, but first I need to make planetrs use an external config file to easy update process and make it less rust-planet.com oriented.

**Comment by remram44** [comment]
>  make it less rust-planet.com oriented.

planet-rust.com is the correct address. I suggest you put it somewhere on the repository landing page or README?

**Comment by Vagdish** [comment]
I mean that, currently, planetrs software is meant for planet-rust.com website: many strings are hard-encoded in code and in templates.

The idea behind planetrs is to provide a planet software for everyone and/or anything. That is not easily achieved for now, through a config file for instance. I plan to make planetrs use a config file before making the atom feed more complete (add authors, resume, etc).
